#!/bin/bash

# Crato log input configuration
# use CSV format


#LOG:path-to-log,tag,severity
LOG:/hello/there,new-tag,info

LOG:/good/bye,tag-2,warn

LOG:/hello/again/you,tag-3,debug

PUBLIC_IP:123.123.312.34,514

PUBLIC_IP:223.123.312.34,714



